file_paths:
  raw_data_dir: ${hydra:runtime.cwd}"data/raw"
  preprocessed_dir: "data/processed"
  augmented_dir: "data/fully_processed"
  train_set_dir: "data/train_set"

resnet_params:
  base_model_name: 'resnet18'
  weights: models.ResNet18_Weights.IMAGENET1K_V1
  input_channels: 1
  
svc_params:
  kernel: 'rbf'
  C: 100
  gamma: 0.0001
  random_state: 42

preprocessing_params:
  target_shape: (192, 256, 256)
  voxel_size: tuple=(2, 2, 2)
  order: int = 4
  mode: str='reflect'
  cval: float=0.0
  output_format: str='numpy'
  min_val: 0
  max_val: 1
  eps: float = 1e-8
  modality: 't1'
  verbose: bool = True
  sigma: 1.5
  order: 2
  mode: 'constant'
  cval: 1.0, 
  truncate: 2.0